services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - include:/var/www/html/include
      - filestore:/var/www/html/filestore
      - ./testdir:/srv/storage/testdir
    networks:
      - frontend
      - backend
    ports:
      - "80:80"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resourcespace
      MYSQL_USER: resourcespace
      MYSQL_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mariadb:
  include:
  filestore:
